language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo add-apt-repository -y ppa:lizardo/ppa
  - sudo apt-get update -qq
  - (cd /tmp && git clone git://github.com/lizardo/blueish.git)
  - sudo apt-get install -qq python-construct python-six python-gi valgrind python-yaml python-dbus
install:
  - sudo apt-get install -qq libdbus-1-dev libglib2.0-dev libudev-dev libical-dev libreadline-dev libsbc-dev
script: ./travis_run.sh
env:
  - COVERAGE=yes
  - COVERAGE=no
matrix:
  exclude:
   - compiler: clang
     env: COVERAGE=yes
